### ISSUE TITLE
Dilution, Stellar Parameters, and MCMC

### ISSUE THREAD

**Issue by dfm** [benmontet/k2-characterization#11]
I've been hacking on trying to include dilution effects into the planet parameters and I don't think that I can do it without resampling the posteriors conditioned on this model. I'm coming around to the opinion that maybe it's actually just better re-run the MCMC chains when we settle on a final set of stellar parameters…

Another point: so far, I've been taking Tim's samples for the stellar parameters and approximating the distribution using a KDE. What do you guys think about just using the multivariate Gaussian instead? We're artificially inflating the errorbars anyways and it seems to me like the Gaussian would capture all the relevant structure. It would be easier to work with :-) Opinions?

**Comment by timothydmorton** [comment]
I'm not sure I understand your first point...are we not settled on using these stellar parameters?  What else are we waiting for on that?  Also maybe I'm not understanding because I'm not sure what exactly "this model" is, etc.

In any case, approximating the stellar parameters as a multivariate Gaussian sounds reasonable to me!

**Comment by benmontet** [comment]
Yeah, I'm happy with these stellar parameters also. The only thing we're
missing is the dilution on those two with AO, and I'll have that for you
shortly. The others shouldn't change.

I'm happy to use a Gaussian, too, but let's be clear that this is what we
do. There are some with a long tail, presumably caused by having some
probability of being slightly evolved, and we'll lose this when we move to
a Gaussian.

**Comment by benmontet** [comment]
There's actually only one with an AO companion that matters for the photometry. This is 201828749, which is 2.0 \pm 0.1 mags fainter. This means 86 \pm 1\% of the light is coming from the primary and 14 \pm 1\% from the secondary.

**Comment by benmontet** [comment]
@dfm was this ever dealt with appropriately?

**Comment by dfm** [comment]
I have just set some code running to do this... Sorry I'd forgotten

**Comment by benmontet** [comment]
Status update?

**Comment by dfm** [comment]
Still running! I'm inclined to just update that in response to referee because I'm not sure if it'll be finished by 4...

**Comment by benmontet** [comment]
Okay. We'll see if we finish by 4 and will decide one way or the other
based on that.
