### ISSUE TITLE
201555883 and the like?

### ISSUE THREAD

**Issue by timothydmorton** [benmontet/k2-characterization#13]
We are saying that we know 201555883 is a period-epoch match with a known EB (201569483).  How deep is the EB signal?  What is the relationship on the detector b/w these two stars?  Are they close by?  On the same CCD column?  How closely are they matched?  

Details are important because my FPPs say "planet."

And have we checked for other period-epoch collisions among our detected signals?

**Comment by benmontet** [comment]
The EV is ~10% deep. They don't necessarily make sense as being closely
matched/on the same column/a 180 degree rotation.

I emailed the K2 team about this and Jeff Coughlin just got back, I'll cc
you in the loop on the reply.

There are no other collisions between planet-like signals in C1 (either
planetary or EBs). I did not yet check for collisions between nearby known
EBs that are not being downlinked and our catalogue.

**Comment by timothydmorton** [comment]
How far away is the EB from our candidate?

**Comment by benmontet** [comment]
Not close enough to interfere directly by PSF overlap. The EB is near the edge of the detctor, and the candidate is several modules away (see figure).
![2_fov](https://cloud.githubusercontent.com/assets/1314530/6581863/0b0f8c3a-c730-11e4-96e8-03496ed48cf6.png)

**Comment by timothydmorton** [comment]
maybe try an ephemeris match using this:  http://www.astrouw.edu.pl/asas/?page=acvs

**Comment by benmontet** [comment]
Nothing within 15 degrees found with that tool. Also doesn't find the 10% deep one that we have in K2. It continuously surprises me how many EBs we don't know about around reasonably bright stars, given how deep they are!

**Comment by benmontet** [comment]
So I don't really know what to do with this one. I don't particularly have the confidence to say "this is definitely an artifact, we just have no idea how" after talking to Tom and Jeff. But it _has_ to be, right? What's the expected number of objects with the same period, phase, and duration? This is the Serial podcast all over again.

I propose we leave it in limbo in our formal tally. In the subsection currently titled "instrumental false positive" I'll note that it formally passes your test, but because of this weirdness that isn't captured by your scheme, we note the possibility that it might be a FP and recommend follow-up both to confirm this system and better understand a potential artifact inherent to Kepler.

Any opposed to that plan?

**Comment by dfm** [comment]
I'd be inclined to say that it's definitely an artifact but I don't have the argument fully. One reason why I'm concerned is that the star is very variable so our systematics model has to pick up more shit than it's supposed to. This means that _maybe_ there's some residual signal from the EB _in the basis_ and somehow the model has to weight that basis very highly to pick up the variability... this is surprising again because it requires a large number of coincidences but there's nothing formal protecting us against it!

Also: this is a pretty marginal transit in a noisy light curve and the in-transit noise appears to be _lower_ than the out-of-transit noise. Let me explore this in more detail...
