### ISSUE TITLE
Notes for FPP table?

### ISSUE THREAD

**Issue by timothydmorton** [benmontet/k2-characterization#19]
Let me know any notes/annotation/etc. that you think should be in the FPP table (e.g. special notes for particular candidates).  I generate it automatically, so best for me to edit the script rather than to edit the .tex directly.

**Comment by benmontet** [comment]
Okay. I'll look closely at it this morning. For now, could you change the
format slightly to match the planet properties table, so that the candidate
name/number get one column in total? (e.g. 201912552.01 instead of
201912552 & 1 )

**Comment by timothydmorton** [comment]
Yup, on it.

**Comment by benmontet** [comment]
Okay, the following we need to discuss somewhere:

201367065: Crossfield et al. planets. What's going on to cause a 0.761 FPP
for one of them?

201505350: Armstrong et al. planets. These are near resonance and have
overlapping transits. I believe this is probably why your code is giving
large FPPs, because the transits are weirdly shaped and changing? They
confirm this system through ground-based TTV detection (which isn't
apparnet in K2 alone)

Period match one you rule out already, good.

201929294 is also a FP, this is a noise-modeling systematic. The star is
really spotted so the assumption that all variability is caused by
spacecraft motion is breaking down. Huge starspot modulation with the same
period as the "candidate"

All the others I am willing to accept at face value.

**Comment by timothydmorton** [comment]
WIth 201367065.01, here's what's going on:  The simulated planet scenarios for an rprs value of 0.0354, all seem to predict mostly deeper transits than what is observed, leaving the EB scenario as a "better" fit.

![pl](https://cloud.githubusercontent.com/assets/1895387/6849538/2683df58-d3aa-11e4-9ad2-a842a113ce9c.png)

I'll talk my way around this...

I'll get on the rest of these notes now.

**Comment by timothydmorton** [comment]
what section in the paper should i refer to for 201929294?

**Comment by benmontet** [comment]
One that we haven't pushed yet. It's going to be part of an expansion
of the "2 candidates one ephemeris" section because we can explain that one
too as funny business in the systematics model caused by spots.

**Comment by timothydmorton** [comment]
ok; can you give that section a label called "sec:systematics"?  I'll refer to that for both cases in the table notes.

**Comment by benmontet** [comment]
Yep, can do.

**Comment by timothydmorton** [comment]
OK; I think the FP table is just about finalized.  Only thing I'm waiting on is the extra depth column in Table 5, in order to know whether or not to add more systems to the (a) designation (cautiously returning to candidate status)....
